name: lexi_mice_detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - ultralytics
    - opencv-python
    - numpy
    - tqdm
    - flask
    - pillow
    - pyyaml
